### ISSUE TITLE
Incorrect config file?

### ISSUE THREAD

**Issue by Dolorousrtur** [FishWoWater/ARCSim-For-SMPL#1]
Hi! Great work building up this repository!

I have installed, but the result on the sample config provided differ from what you show in imgs/demo_handsup.gif. Maybe I should change the config somehow?

I run it with the command from readme and I haven't changed any configuration file. 

`./build-Release/bin/arcsim_0.2.1 play smpl_demo/pbns_sbs_male.json vis`

Could you check it up? Thanks in advance!

https://user-images.githubusercontent.com/9041552/176212432-c97b07be-4fe7-4284-825a-0fcf850d0642.mp4

**Comment by FishWoWater** [comment]
Hi! Thanks for pointing out this problem. 

This is due to the inconsistency between the motion and code logic. At the very beginning(where the previous video came from), SMPL motion is first transformed into arcsim coordinate frame(z upwards), while in the latest version, smpl motion is simulated in  OpenGL coordinate frame (x right, y upwards, z outside the screen).

I have updated the motion file and demo video. You can have a look at that~

Best

**Comment by Dolorousrtur** [comment]
Thanks for the quick response! Seems that the new config `jump.json` uses garment meh `meshes/vto_tshirt.obj` that is not added to this repository. 

I used `tshirt.obj` from [this repo](https://github.com/isantesteban/vto-dataset) and it works like a charm. But maybe you'd want to add it to this repo as well.

**Comment by FishWoWater** [comment]
@Dolorousrtur Thanks for your kind words and apologize for my carelessness, added now
