### ISSUE TITLE
Some artifacts when the body parts are close to other parts.

### ISSUE THREAD

**Issue by StevenLiuWen** [FishWoWater/ARCSim-For-SMPL#4]
Hi, @FishWoWater ,

Some artifacts will be presented when the body parts are close to other parts, shown as follows.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/22798411/176590331-825649b9-4b72-418a-9060-5de12e372602.png">

![image](https://user-images.githubusercontent.com/22798411/176590427-347a11f5-ecec-4b58-becd-ffdc86dc6895.png)

Is there any solution to handle these cases? Looking forward to your answer and thanks in advance.

**Comment by FishWoWater** [comment]
Hi, @StevenLiuWen 

This is highly relevant to the motion seqeunce. Given one motion sequence, human body is firstly interpolated from T-pose to the starting frame of that sequence. This interpolation can be unreasonable in some cases(different from its real trajectory) and causes problem in collision resolving. Also, problems can occur as the motion goes on (e.g. collision resovling fails to converge, smaller time steps can alleviate this issue but it's diffuclt to completely avoid it). As the practice in many publications, the interpolated frames or frames with problem are simply truncated and discarded. 

I have generated some motion files according to https://github.com/isantesteban/vto-dataset. I have run most of them successfully and you can have a try. [vtoposes.zip](https://github.com/FishWoWater/ARCSim-For-SMPL/files/9016488/vtoposes.zip). There are some other things you need to pay attention to, for example, set the frame time in each config to exactly 1/3 seconds, otherwise it wouldn't be perfectly aligned with MoCap Sequence. 

Sorry I am going through busy months and can't provide detailed doc or configuration here, just put one for demonstration.

**Comment by StevenLiuWen** [comment]
I see, thanks for your patient reply.
