### ISSUE TITLE
Weird Simulation Result

### ISSUE THREAD

**Issue by kunkun0w0** [FishWoWater/ARCSim-For-SMPL#6]
Thanks for this cool project. I have encountered some problems when simulating.
When running the jump demo, I find a weird result when t>1.0s.

![image](https://user-images.githubusercontent.com/56219029/191242467-366c4804-7f9c-4d68-9e68-e1f85a44b720.png)

Could you give me some suggestions to fix this bug?

**Comment by FishWoWater** [comment]
Hi! @kunkun0w0 

I am not sure whether SMPL simulation is consistent with the puppet model simulation. Some works(e.g. TailorNet) do point that simulation can fail sometimes (mostly when the the body itself comes close since collision handing should be tricky). 

I have no good ideas to avoid this completely, but you can use truncated / specified motions to ensure the body part is well separated), Refer to #4
